_target_: src.models.surge_ff_module.SurgeFeedForwardModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

scheduler: null

net:
  _target_: src.models.components.residual_mlp.CNNResidualMLP
  in_dim: ${data.signal_length}
  channels: 24
  encoder_blocks: 4
  trunk_blocks: 4
  hidden_dim: 384
  out_dim: ${mul:${data.k},2}
  kernel_size: 7
  norm: bn

loss_fn: mse

# compile model for faster training with pytorch 2.0
compile: true
