_target_: src.models.components.transformer.AudioSpectrogramTransformer
d_model: 512
n_heads: 8
n_layers: 8
n_conditioning_outputs: 8
patch_size: 16
patch_stride: 10
input_channels: 2
spec_shape: [128, 401]
