# @package _global_

defaults:
  - _self_
  - data: surge
  - model: surge_flow
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: none
  - experiment: null

task_name: "eval"

# run name for output directory
run_name: "eval"

tags: ["dev"]
mode: test

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
